### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Thewisem** [FilenCloudDienste/filen-mobile#2]
Add your app to the fdroid store, an open source store that is filled with open source apps

**Comment by b3pio** [comment]
Inclusion on F-Droid app store would be fantastic, if not the main f-droid repo then consider IzzyOnDroid repo.
Personally I'd also like to see you consider completely removing the 'Google Firebase Analytics' tracker or at least replacing with a privacy respecting analytics tracker in future versions please.

**Comment by julianfairfax** [comment]
Please do add this app to F-Droid!

**Comment by DanielProg39** [comment]
> Inclusion on F-Droid app store would be fantastic, if not the main f-droid repo then consider IzzyOnDroid repo. Personally I'd also like to see you consider completely removing the 'Google Firebase Analytics' tracker or at least replacing with a privacy respecting analytics tracker in future versions please.

Yes, as of a great replacement of Google Analitycs I would recommend [Matomo](https://matomo.org/), which is privacy friendly, self-hosted and FOSS

**Comment by Loki-L1130** [comment]
> Yes, as of a great replacement of Google Analitycs I would recommend [Matomo](https://matomo.org/), which is privacy friendly, self-hosted and FOSS

Plausible is also a great alternative to Matomo simple and easier to use too in my Opinion.

**Comment by DanielProg39** [comment]
> > Yes, as of a great replacement of Google Analitycs I would recommend [Matomo](https://matomo.org/), which is privacy friendly, self-hosted and FOSS
> 
> Plausible is also a great alternative to Matomo simple and easier to use too in my Opinion.

I agree with you, but if developers are used to Google Analitycs, Matomo will be more familiar in terms of functionality and interface

**Comment by Dwynr** [comment]
We actually don't use any lind of analytics for our app. Just take a look at the source, you won't find any, neither Google Firebase or anything else

**Comment by Toby4213** [comment]
> We actually don't use any kind of analytics for our app. Just take a look at the source, you won't find any, neither Google Firebase nor anything else

According to this analysis it does... https://reports.exodus-privacy.eu.org/en/reports/203669/
Also the build.gradle file includes the com.google.gms class

**Comment by Dwynr** [comment]
The scan just looks for google signatures. We never actually initialize any trackers, the gms lib is imported because it includes more functionality than just a tracker.

**Comment by Toby4213** [comment]
Ok thank you, makes sense

**Comment by IzzySoft** [comment]
Without any description or screenshots I actually do mind :wink: How about adding [Fastlane Structures](https://gitlab.com/-/snippets/1895688) to this repo? F-Droid would want to have that, too, once you reach that.

But my scanner would find the same structures and complain, let me check…

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Play Services Places Placereport (/com/google/android/gms/places_placereport): NonFreeDep,NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): Tracking

5 offenders.
```

Ugh… even louder…

> We never actually initialize any trackers,

Then why including them at all? Did you try to [exclude](https://stackoverflow.com/a/56853571/2533433) them?

> the gms lib is imported because it includes more functionality than just a tracker.

And which of those do you need so urgently to taint a FOSS app with a proprietary dependency? :wink:

**Comment by bingoxo** [comment]
@IzzySoft for description and screenshots you can use : https://play.google.com/store/apps/details?id=io.filen.app&hl=en_US&gl=US

as for the other stuff the devs would need to answer those as i'm just an end user , they are revamping the app though so hopefully some or even all the issues you mentioned will be fixed in the near future

**Comment by IzzySoft** [comment]
@bingoxo confirmed: I can initially import metadata from that (I have a tool in my repo that does this). Though the other issues must be addressed first.

**Comment by bingoxo** [comment]
@IzzySoft can you please check if the latest update is suitable ?

**Comment by IzzySoft** [comment]
Better already:

```
Offending libs:
---------------
* Play Install Referrer Library (/com/android/installreferrer): NonFreeDep,NonFreeNet,Tracking
* Android Market (/com/google/android/finsky): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep

3 offenders.
```

Not yet suitable for F-Droid (no NonFreeDep allowed) – and unfortunately too big for my repo (limit: ~30 MB)… Maybe an armeabi only build could fit in, that should be slightly below the 30 MB limit.

**Comment by nep2ner** [comment]
It would be great to see a fully FOSS version of Filen on F-Droid! This would put me all in on the Filen train. If Filen offered this, they would be the only player in this space, which is surely a competitive edge.

**Comment by julianfairfax** [comment]
> The scan just looks for google signatures. We never actually initialize any trackers, the gms lib is imported because it includes more functionality than just a tracker.

Yeah same question as Izzy, what functionality is there that you're using? The app worked fine last I tried on my degoogled device. If there actually is something missing feature, I'm sure it'd be fine if it was only available on the Google Play Store version, and if a separate version of the app existed on F-Droid without it.

**Comment by julianfairfax** [comment]
I can't find where GMS is referenced in the code. And I still don't understand why it's needed.

**Comment by IzzySoft** [comment]
It's most likely a dependency of a dependency, so it becomes only visible at build time (when all the dependencies are resolved) – an ugly fact with all Node stuff. Have you tried `npm list` (see https://stackoverflow.com/a/47040266) to find out?

**Comment by Flam3z** [comment]
New User here, is there any progress on adding this to the f-droid store? considering there are many who are trying to move away from google. Adding it there would of course bring more customers.

**Comment by julianfairfax** [comment]
> We actually don't use any kind of analytics for our app. Just take a look at the source, you won't find any, neither Google Firebase nor anything else

Any progress on F-Droid inclusion then? Why does it say it requires GMS? @IzzySoft does F-Droid's scanner show any useful details? I could just open a request for packaging there?

**Comment by IzzySoft** [comment]
@julianfairfax you could open an RFP, but we would be unable to process it unless above quoted dependencies are gone. And those results are of one of the scanners used at F-Droid (which you find in the issuebot results as "APK library scanner" – I wrote that one). And again as pointed out: if it wasn't explicitly included for some reason, it was dragged in by a dependency.

**Comment by MalteKiefer** [comment]
I added to my personal repo:

https://repo.beli3ver.de/

It is not F-Droid but an F-Droid repo.

**Comment by licaon-kter** [comment]
This draft recipe **metadata/io.filen.app.yml**
```
AntiFeatures:
  - NonFreeNet
Categories:
  - Network
License: AGPL-3.0
AuthorName: Filen
AuthorEmail: support@filen.io
AuthorWebSite: filen.io
SourceCode: https://github.com/FilenCloudDienste/filen-mobile
IssueTracker: https://github.com/FilenCloudDienste/filen-mobile/issues

AutoName: Filen

RepoType: git
Repo: https://github.com/FilenCloudDienste/filen-mobile

Builds:
  - versionName: 2.0.18
    versionCode: 218
    commit: bdf224f6881416cf9635fb0723df5190081498fa
    subdir: android/app
    sudo:
      - sysctl fs.inotify.max_user_watches=524288
      - apt-get update || apt-get update
      - apt-get install -y openjdk-11-jdk-headless
      - update-alternatives --auto java
      - curl -Lo node.tar.xz https://nodejs.org/dist/v16.16.0/node-v16.16.0-linux-x64.tar.xz
      - echo "edcb6e9bb049ae365611aa209fc03c4bfc7e0295dbcc5b2f1e710ac70384a8ec node.tar.xz"
        | sha256sum -c -
      - tar xJf node.tar.xz
      - cp -a node-v16.16.0-linux-x64/. /usr/local/
      - npm i -g npm@8.5.5
    init: npm install
    gradle:
      - yes
    scanignore:
      - node_modules/jsc-android
      - node_modules/react-native/android
    scandelete:
      - node_modules/
    ndk: r21e

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 2.0.18
CurrentVersionCode: 218
```
...fails:
```
2022-08-10 14:52:40,844 DEBUG: > bash -x -c -- npm install
+ npm install
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.16.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.16.0>
npm notice Run `npm install -g npm@8.16.0` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: filen-mobile@2.0.18
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16.8.0  || ^17.0.0 || ^18.0.0" from react-use@17.4.0
npm ERR!   node_modules/react-use
npm ERR!     react-use@"^17.3.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.2.0" from react-dom@18.2.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^16.8.0  || ^17.0.0 || ^18.0.0" from react-use@17.4.0
npm ERR!   node_modules/react-use
npm ERR!     react-use@"^17.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/vagrant/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2022-08-10T14_52_41_054Z-debug-0.log
ERROR: Could not build app io.filen.app: Error running init command for io.filen.app:2.0.18
```

As usual node apps need hand from the dev, so which npm? nodejs? special steps?
